apiVersion: v1
kind: Service
metadata:
  labels:
    app: account-link-api
    app.kubernetes.io/component: account-link-api
    app.kubernetes.io/instance: account-link-api
    app.kubernetes.io/name: account-link-api
    app.kubernetes.io/part-of: account-link-api-context
  name: account-link-api
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: account-link-api
  type: ClusterIP
