apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: billing-account-api
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: billing-account-api
    app.kubernetes.io/name: billing-account-api
    app.kubernetes.io/part-of: billing-context
    app.openshift.io/runtime: dotnet
  name: billing-account-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-account-api
  template:
    metadata:
      labels:
        app: billing-account-api
        deploymentconfig: billing-account-api
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: billing-account-configmap
        - secretRef:
            name: billing-account-secret
        image: billing-account-api:latest
        imagePullPolicy: Never
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        name: billing-account-api
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          successThreshold: 1
        resources:
          limits:
            cpu: 600m
            memory: 2560Mi
          requests:
            cpu: 100m
            memory: 512Mi
        startupProbe:
          failureThreshold: 35
          httpGet:
            path: /health/startup
            port: 8080
          periodSeconds: 6
        volumeMounts:
        - mountPath: /tmp
          name: tmp-dir
      volumes:
      - emptyDir: {}
        name: tmp-dir
