apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-gateway
  template:
    metadata:
      labels:
        app: graphql-gateway
    spec:
      containers:
      - name: graphql-gateway
        image: graphql-gateway
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          protocol: TCP