apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-api
    app.kubernetes.io/component: user-api
    app.kubernetes.io/instance: user-api
    app.kubernetes.io/name: user-api
    app.kubernetes.io/part-of: user-context
  name: user-api
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: user-api
  type: ClusterIP
