apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongodb
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          image: mongodb/mongodb-community-server:latest
          args: ["--bind_ip_all", "--replSet", "devrs"]
          resources:
            limits:
              memory: 1024Mi
              cpu: 500m
            requests:
              memory: 256Mi
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /scripts/replicaSetInit.js
              name: mongodb-cm0
              subPath: replicaSetInit.js
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: replicaSetInit.js
                path: replicaSetInit.js
            name: mongodb-cm0
          name: mongodb-cm0